### ISSUE TITLE
Requests Session no longer accepts params

### ISSUE THREAD

**Issue by kracekumar** [yuvipanda/python-mwapi#1]
From `requests 1.0.0` api for `Session` doesn't accept any parameter. Following code will break.
```
from mwapi import MWApi
m = MWApi(host="http://ta.wiktionary.org")
```
Link to new Api: https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L137

**Comment by halfak** [comment]
It looks like this was fixed by https://github.com/yuvipanda/python-mwapi/pull/2
